### ISSUE TITLE
README: Don't recommend redis distlock

### ISSUE THREAD

**Issue by dgryski** [minio/dsync#29]
Distlock is not a safe distributed locking algorithm.

http://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html

**Comment by harshavardhana** [comment]
http://antirez.com/news/101 - looks like the jury is out there?

**Comment by dgryski** [comment]
While Antirez has shown himself to be an excellent C programmer, he's a poor distributed system engineer.  Martin Kleppmann is a distributed system research at Cambridge.  I'm likely to trust his analysis more.

**Comment by maximecaron** [comment]
Another common way to implement distributed lock is to simply use Lease.
Xtreemfs use the FLease algorithm that is a Lease built on top of Paxos register: http://www.xtreemfs.org/publications/flease_paper_ipdps.pdf

The main difference I see is that stale lock are automatically released if the server can't renew the lease in time.  Also the state change is linearizable and crash resistant.

**Comment by fwessels** [comment]
We are not "recommending" redislock, it is just another approach that may work for some in some cases and not in other cases.

It is not meant to be a conclusive list, for sure there will be other approaches as well.
