### ISSUE TITLE
Sending unlock messages in a go-routine makes ``DRWMutex.[R]Lock()`` racy

### ISSUE THREAD

**Issue by krisis** [minio/dsync#7]
``DRWMutex``'s ``[R]Lock()`` method sends unlock messages (see ``sendRelease``), when quorum number of positive responses weren't received, on nodes that granted lock. This is executed concurrently to subsequent lock retries until quorum is met. The following order of events could cause in more RPC messages exchanged amongst the nodes synchronizing using ``dsync.DRWMutex`` than optimal.

Consider a set of 4 nodes (i.e, 4 lock servers).
1. Lock("test") -> [true, false, false, true]; Quorum not met.
2. Unlock before locking is retried -> [true, , _, rpc.ErrShutdown], where "" represents "don't care"
3. Attempting lock on "test" again -> [true, _, _, blocked]; i.e, this lock message raced the unlock message from Step 3.
This is not protected by the underlying TCP's message ordering since connectLazy replaces rpcClient.rpc with newer socket after every failed Call (or failed rpc.DialHTTP).

**Comment by fwessels** [comment]
In Step 3, if nodes 2 & 3 would also grant the lock than quorum would be met and the lock would be granted (even if node 4 is still in blocked/network error state).
There is a (small) backoff window before trying to lock again, depending on timing it could be suboptimal in terms of number of messages, but it would not lead to incorrect behavior?

**Comment by krisis** [comment]
@fwessels, the lock mentioned in step 3 on "test' is different from the lock mentioned in step 1. I am not referring to the lock messages that appear out of retrying due to previous attempts at failing to lock. Does it make sense now?

**Comment by fwessels** [comment]
I see, this order of events can indeed happen.

**Comment by fwessels** [comment]
While the above order of events can maybe lead to not the most efficient way of dealing with it, it should not lead to incorrect behaviour (bugs).

One can also think of other scenarios that show correct behaviour but are suboptimal in terms of eg number of messages exchanged. While it is probably possible to optimize these scenarios it would complicate the code (and hence maybe introduce new bugs), so I think this is not worth the effort (and risk).
